on: [push]

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send message via Matrix
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          ALL_MSGS=""
          for i in ${{ join(github.event.commits.*.id, ' ') }}; do
            MSG=$(git --no-pager show -s --format='%h <b>%an</b>: %s' $i)
            # From this link the newline character is: %0A
            # https://github.community/t/set-output-truncates-multiline-strings/16852
            ALL_MSGS="$ALL_MSGS$MSG<br>%0A"
          done
          echo "::set-output name=COMMIT_MESSAGE::$ALL_MSGS"
        id: commit-message
      - uses: narodnik/matrix-action@main
        with:
          server: 'matrix.dark.fi'
          room-id: '!MODZOZydPqCRdulXmR:dark.fi'
          #access_token: ${{ secrets.MATRIX_TOKEN }}
          status: 'OK'
          user: 'narodnik'
          password: ${{ secrets.MATRIX_PASSWORD }}
          message: '${{ steps.commit-message.outputs.COMMIT_MESSAGE }}'
          #- name: Send message to test channel
          #  id: matrix-chat-message
          #  uses: fadenb/matrix-chat-message@v0.0.6
          #  with:
          #    homeserver: 'dark.fi'
          #    token: ${{ secrets.MATRIX_TOKEN }}
          #    channel: '!MODZOZydPqCRdulXmR:dark.fi'
          #    message: |
          #      This is an *example message* using **markdown** for formatting.\
          #      Use a `\` character at the end of a line to cause a linebreak (the whole message is treated as markdown).\
          #      You can use variables like ${{ github.sha }} anywhere.

